language: node_js
cache:
  bundler: true
  directories:
  - node_modules # NPM packages
sudo: false
dist: trusty
node_js:
  - "7"
# safelist for specific branches for travis to test
branches:
  only:
  - master
  - develop
  - develop-1.2
addons:
  chrome: stable
  firefox: "latest"
  apt:
    packages:
    - libappindicator1
    - fonts-liberation
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - npm install --only=dev
install:
  - travis_wait 20 npm run build
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
script:
  - npm test
notifications:
  slack: studykik:nxDZXJcNFYdWoXibXQ9T0013
after_success: 'npm run coveralls'
skip_cleanup: true
