language: node_js
cache:
  bundler: true
  directories:
  - node_modules # NPM packages
sudo: false
dist: trusty
node_js:
  - "7"
# safelist for specific branches for travis to test
branches:
  only:
  - master
  - release
  - develop
before_script:
  - npm install --only=dev
script:
  - npm run lint
  - npm run build
  - npm test
notifications:
  slack: studykik:nxDZXJcNFYdWoXibXQ9T0013
after_success: 'npm run coveralls'
skip_cleanup: true
